apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
  namespace: garage-management
spec:
  backoffLimit: 2
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-registry
      restartPolicy: Never
      containers:
        - name: db-migrator
          image: DB_MIGRATOR_IMAGE
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
