name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Add .NET tools to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Start Sonar analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin `
            /k:"kmlyteixeira_garage-management-api-dotnet" `
            /o:"kmlyteixeira" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.cs.cobertura.reportsPaths="TestResults/Cobertura.xml" `
            /d:sonar.coverage.exclusions="**/Migrations/**,**/*Dto.cs,**/*CreateDto.cs,**/*UpdateDto.cs,**/*CreateUpdateDto.cs,**/*GetListInputDto.cs"

      - name: Build
        run: dotnet build --no-incremental

      - name: Run tests with coverage
        run: |
          dotnet test .\test\GarageManagement.Domain.Tests\GarageManagement.Domain.Tests.csproj `
            --no-build `
            --collect:"XPlat Code Coverage" `
            --results-directory TestResults `
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

          dotnet test .\test\GarageManagement.Application.Tests\GarageManagement.Application.Tests.csproj `
            --no-build `
            --collect:"XPlat Code Coverage" `
            --results-directory TestResults `
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

          dotnet test .\test\GarageManagement.EntityFrameworkCore.Tests\GarageManagement.EntityFrameworkCore.Tests.csproj `
            --no-build `
            --collect:"XPlat Code Coverage" `
            --results-directory TestResults `
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

      - name: Merge coverage reports
        run: |
          reportgenerator `
            -reports:"TestResults/**/coverage.cobertura.xml" `
            -targetdir:"TestResults" `
            -reporttypes:"Cobertura"

      - name: Debug coverage files
        run: Get-ChildItem -Recurse TestResults

      - name: Finish Sonar analysis
        if: always()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"